### ISSUE TITLE
Use of Math.random to generate salt is potentially predictable

### ISSUE THREAD

**Issue by boutell** [davidwood/node-password-hash#6]
I had developed my own implementation of hashPassword() before coming across yours. I think I should standardize on yours and recommend it. It would be nice if your salts were up to a cryptographic standard of randomness. Everything else about your code looks great.

The use of Math.random to generate the salt is potentially predictable, since Math.random is seeded from the system time at start time and then it's a known algorithm that permutes from one result to the next... I'm not a hardcore mathematician, but I gather one should avoid this sort of thing for cryptography.

Here's my code for truly random salts on Linux and MacOS:

```
    // Generate 8 highly random hex digits (from 4 random bytes)
    var i = 0;
    var b = new Buffer(4);
    // /dev/urandom is a virtual device, we are not paying a meaningful penalty for sync here
    var fd = fs.openSync('/dev/urandom', 'r');
    fs.readSync(fd, b, 0, 4, 0);
    fs.closeSync(fd);
    cryptoState.salt = b.toString('hex');
```

This would need a little work to work right for your purposes because the number of possible characters in each position for your salts doesn't go evenly into 256. I just use hex characters so I know that one random byte is good for exactly two salt characters.

I'm using /dev/urandom because if the system runs out of truly random bytes (collected by measuring the microsecond timing of network events and such) it can fall back on a pseudorandom number generator seeded by those rather than blocking indefinitely. It's actually possible to exhaust /dev/random and wind up blocking until something random is observed by the operating system (:

Thanks for a good module!

**Comment by davidwood** [comment]
Thanks for the suggestion!

node 0.5.8 introduced `crypto.randomBytes`, which generates cryptographically strong pseudo-random data.  I've updated the `generateSalt` function to check if `crypto.randomBytes` is supported and if it is, it uses it to generate the salt.  If not, `Math.random` is still used.

I know this means that people still using node 0.4.x will still get salts generated using `Math.random`, but instead of reading from `/dev/random` or `/dev/urandom`, I'd rather encourage people to update to the latest stable version of node.  I've included a note in the readme, making explaining how the salt is generated.

This change has been published to npm as version 1.2.1
